# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20190529_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='', verbose_name='picture/'),
        ),
    ]
